name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code       
    uses: actions/checkout@v1  

    - name: Build docker container
      run: docker build -t bratzzie/docker-react -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true bratzzie/docker-react npm run test -- --coverage
