name: Docker Image CI with AWS Elastic Beanstalk

env:
  APP_NAME: docker-react
  APP_ENV: Dockerreact-env
  S3_BUCKET: docker-react-studying
  AWS_REGION: eu-west-3
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
  
on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t bratzzie/docker-react -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true bratzzie/docker-react npm run test -- --coverage

  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: ech
      run: echo ${{env.PIPELINE_ID}}
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r ${{env.APP_NAME}}-${{env.PIPELINE_ID}}.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: ${{env.APP_NAME}}
        environment_name: ${{env.APP_ENV}}
        version_label: "${{env.PIPELINE_ID}}"
        region: ${{env.AWS_REGION}}
        deployment_package: "${{env.APP_NAME}}-${{env.PIPELINE_ID}}.zip"
